#!/bin/bash
set -e
MYHOSTNAME=autoscale.dyndns.org

if grep -q "^CLOUD_" /etc/environment;then
    sed -i '/^CLOUD_/d;/^$/d' /etc/environment
fi
cat <<EOF>>/etc/environment
CLOUD_USER="$1"
CLOUD_KEY="$2"
CLOUD_AUTH_URL="$3"
EOF

source /etc/environment
export CLOUD_AUTH_URL CLOUD_KEY CLOUD_USER
export DEBIAN_FRONTEND=noninteractive

apt-get -y install memcached python-memcache nginx ddclient
sed -i 's/127.0.0.1/loadbalancer.local/' /etc/memcached.conf
service memcached restart

/usr/local/bin/dynamic-host.py

ufw allow in on eth1 to any port 11211 proto tcp  || :
ufw allow 80 || :

rm -f /etc/nginx/sites-enabled/default
cat <<EOF>/etc/nginx/sites-enabled/clouddemo
include /etc/nginx/lb.conf;
server {
	listen   80; ## listen for ipv4
	listen   [::]:80 default ipv6only=on; ## listen for ipv6
	server_name  ${MYHOSTNAME};
	access_log  /var/log/nginx/clouddemo.log;

    location / {
       proxy_pass http://clouddemo;
     }
}
EOF

service nginx restart

cat <<EOF>/etc/ddclient.conf
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

protocol=dyndns2
use=web, web=checkip.dyndns.com, web-skip='IP Address'
server=members.dyndns.org
login=chmouelrack2
password='rackspace'
${MYHOSTNAME}

EOF
service ddclient restart
