#!/bin/bash
ADMIN_DBPASS=$1
GUESTBOOK_DBPASS=$2

if [[ -z ${ADMIN_DBPASS} ]];then
    ADMIN_DBPASS="randomString33"
fi

if [[ -z ${GUESTBOOK_DBPASS} ]];then
    GUESTBOOK_DBPASS="blaha331002"
fi

export DEBIAN_FRONTEND=noninteractive
apt-get install mysql-server ufw ddclient -y

mysqladmin password ${ADMIN_DBPASS}
cat <<EOF>~/.my.cnf
[client]
password = ${ADMIN_DBPASS}
EOF

sed -i -n '/bind-address/ { s/127.0.0.1/0.0.0.0/ };p' /etc/mysql/my.cnf

restart mysql

mysqladmin create guestbook
mysql -e "grant all privileges on guestbook.* to guestbook@'demo-web1' identified by '${GUESTBOOK_DBPASS}'"


exit

cat <<EOF>/etc/ddclient.conf
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

protocol=dyndns2
use=web, web=checkip.dyndns.com, web-skip='IP Address'
server=members.dyndns.org
login=chmouelrack
password='rackspace'
demo-db1.dyndns.info

EOF
/etc/init.d/ddclient start

#Networking
#ufw allow proto tcp from demo-web1 to any port 3306

